version: '3'
services:
 mongodb:
  image: mongo
  ports:
   - 27017:27017
  environment:
   - MONGO_INITDB_ROOT_USERNAME = admin
   - MONGO_INITDB_ROOT_PASSWORD = password
  mongo-express:
   image: mongo-express
   ports: 
    - 8080:8080
   environment:
   - MONGO_INITDB_ROOT_USERNAME = admin
   - MONGO_INITDB_ROOT_PASSWORD = password
    
#to execute this file -> docker-compose -f docker-compose.yaml<file name> up -> for starting the containers
# docker-compose -f docker-compose.yaml<file name> up -d -> for id
# docker-compose -f docker-compose.yaml<file name> down -> for stopping the containers